### PR TITLE
add "Coming Soon" to Blog and Wiki views

### PR DESCRIPTION
**Pull request by Bcama**

### CODE REVIEW

**Comment by virsaviya** [comment]
This looks great!  Except the PR is for `coming-soon` > `master`.  Could you change it to `coming soon` > `client-setup`?  Thanks!

Will approve it as soon as that's fixed.

**Comment by Bcama** [comment]
Switched the base branch. Sorry about that!

**Review by virsaviya — APPROVED** [review]
Learning opportunity!  

Looks good - I'm closing this out.  Yay, your first PR!

**Comment by virsaviya** [comment]
Clearly I'm still learning Github too 😂

I've approved the commit.  Now it's back to you @Bcama, to merge and close out this PR.

**Pull request merged**
